
package com.amba.service.mfa.stub.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SoapFault", targetNamespace = "http://ws.csd.rsa.com")
public class AdaptiveAuthenticationSoapFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SoapFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AdaptiveAuthenticationSoapFault(String message, SoapFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AdaptiveAuthenticationSoapFault(String message, SoapFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.lt.auth.service.stub.client.SoapFaultType
     */
    public SoapFaultType getFaultInfo() {
        return faultInfo;
    }

}
