
package com.amba.service.mfa.stub.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AsyncAdaptiveAuthentication", targetNamespace = "http://ws.csd.rsa.com", wsdlLocation = "file:/C:/Users/pratap.sawant/Downloads/lt-service-auth/lt-service-auth/lt-service-auth/src/main/resources/wsdl/AdaptiveAuthentication.wsdl")
public class AsyncAdaptiveAuthentication
    extends Service
{

    private final static URL ASYNCADAPTIVEAUTHENTICATION_WSDL_LOCATION;
    private final static WebServiceException ASYNCADAPTIVEAUTHENTICATION_EXCEPTION;
    private final static QName ASYNCADAPTIVEAUTHENTICATION_QNAME = new QName("http://ws.csd.rsa.com", "AsyncAdaptiveAuthentication");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/pratap.sawant/Downloads/lt-service-auth/lt-service-auth/lt-service-auth/src/main/resources/wsdl/AdaptiveAuthentication.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ASYNCADAPTIVEAUTHENTICATION_WSDL_LOCATION = url;
        ASYNCADAPTIVEAUTHENTICATION_EXCEPTION = e;
    }

    public AsyncAdaptiveAuthentication() {
        super(__getWsdlLocation(), ASYNCADAPTIVEAUTHENTICATION_QNAME);
    }

    public AsyncAdaptiveAuthentication(WebServiceFeature... features) {
        super(__getWsdlLocation(), ASYNCADAPTIVEAUTHENTICATION_QNAME, features);
    }

    public AsyncAdaptiveAuthentication(URL wsdlLocation) {
        super(wsdlLocation, ASYNCADAPTIVEAUTHENTICATION_QNAME);
    }

    public AsyncAdaptiveAuthentication(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ASYNCADAPTIVEAUTHENTICATION_QNAME, features);
    }

    public AsyncAdaptiveAuthentication(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsyncAdaptiveAuthentication(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AsyncAdaptiveAuthenticationInterface
     */
    @WebEndpoint(name = "AsyncAdaptiveAuthentication")
    public AsyncAdaptiveAuthenticationInterface getAsyncAdaptiveAuthentication() {
        return super.getPort(new QName("http://ws.csd.rsa.com", "AsyncAdaptiveAuthentication"), AsyncAdaptiveAuthenticationInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AsyncAdaptiveAuthenticationInterface
     */
    @WebEndpoint(name = "AsyncAdaptiveAuthentication")
    public AsyncAdaptiveAuthenticationInterface getAsyncAdaptiveAuthentication(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.csd.rsa.com", "AsyncAdaptiveAuthentication"), AsyncAdaptiveAuthenticationInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASYNCADAPTIVEAUTHENTICATION_EXCEPTION!= null) {
            throw ASYNCADAPTIVEAUTHENTICATION_EXCEPTION;
        }
        return ASYNCADAPTIVEAUTHENTICATION_WSDL_LOCATION;
    }

}
