
package com.amba.service.mfa.stub.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AsyncAdaptiveAuthenticationInterface", targetNamespace = "http://ws.csd.rsa.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AsyncAdaptiveAuthenticationInterface {


    /**
     * 
     * @param request
     */
    @WebMethod(action = "rsa:notify:Notify")
    @Oneway
    @RequestWrapper(localName = "notify", targetNamespace = "http://ws.csd.rsa.com", className = "com.lt.auth.service.stub.client.Notify")
    public void notify(
        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        NotifyRequest request);

    /**
     * 
     * @param request
     */
    @WebMethod(action = "rsa:analyze:Analyze")
    @Oneway
    @RequestWrapper(localName = "analyze", targetNamespace = "http://ws.csd.rsa.com", className = "com.lt.auth.service.stub.client.Analyze")
    public void analyze(
        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        AnalyzeRequest request);

}
